services:
  localstack:
    build:
      context: ./localstack
    init: true
    ports: [4566:4566]
    environment:
      - SERVICES=s3
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*