version: "3.8"

services:
  localstack:
    build:
      context: ./localstack
    init: true
    ports: [4566:4566]
    environment:
      - SERVICES=s3
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    build:
      dockerfile: ./postgresql/Dockerfile
    ports: [61001:61001]
    command: >-
      -p 61001
      -c 'log_statement=all'
      -c 'log_connections=on'
      -c 'log_disconnections=on'
      -c 'logging_collector=on'
      -c 'log_destination=stderr'
      -c 'log_directory=/var/lib/postgresql/logs'
    volumes: 
      - ./postgresql/logs:/var/lib/postgresql/logs
      - ./postgresql/init_sql:/docker-entrypoint-initdb.d
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro