name: cache-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-test:
    name: CACHE Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Localstack layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-localstack
          key: buildx-localstack-${{ github.ref }}-${{ hashFiles('docker/localstack/**') }}

      - name: Cache Postgres layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-postgres
          key: buildx-postgres-${{ github.ref }}-${{ hashFiles('docker/postgresql/**') }}

      - name: Build Localstack image with cache
        uses: docker/build-push-action@v5
        with:
          context: docker/localstack
          file: docker/localstack/Dockerfile
          tags: localstack-custom:latest
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-localstack
          cache-to: type=local,dest=/tmp/.buildx-cache-localstack

      - name: List docker/postgresql directory
        run: ls -l docker/postgresql

      - name: Build Postgres image with cache
        uses: docker/build-push-action@v5
        with:
          context: docker/postgresql
          tags: postgres-custom:latest
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-postgres
          cache-to: type=local,dest=/tmp/.buildx-cache-postgres

      - name: docker-compose up
        working-directory: docker
        run: docker compose up -d

      - name: Check Localstack container status
        run: docker ps -a
