name: cache-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-test:
    name: CACHE Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}-${{ hashFiles('docker/localstack/**') }}
          restore-keys: |
            buildx-${{ github.ref }}-

      - name: Build Localstack image with cache
        uses: docker/build-push-action@v5
        with:
          context: docker/localstack
          tags: localstack-custom:latest
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: docker-compose up
        working-directory: docker
        run: docker compose up -d

      - name: Check Localstack container status
        run: docker ps
